### ISSUE TITLE
auro-tab: update issue template to include exit criteria 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-tabs#7]
### General Support Request

See `.github/ISSUE_TEMPLATE/feature_request.yml` and `.github/ISSUE_TEMPLATE/general-support.yml` and notice that there is not a field for `exit criteria`.

### Possible Solution

Update with the following content 

```
  - type: textarea
    id: exit-criteria
    attributes:
      label: Exit criteria
      description: Define your issue's exit criteria
      placeholder: "This issue can be closed once the error has been corrected. Any additional scope e.g. updates or refactors, should be discussed PRIOR to adding scope to this issue."
```

### Exit criteria 

This issue can be closed once the issue templates have been updated with exit criteria information allowing users to submit this content in the issue template form.
